services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "4001:8080"
    volumes:
      - ./open-webui_data:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=/ollama
      - WEBUI_SECRET_KEY=sua_chave_secreta_aqui
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always