[project]
name = "speech-to-text"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Diogo Passos Perdigão Britto", email = "diogopbritto@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "numpy>=2.5.2",
    "pyperclip>=1.11.0",
    "python-dotenv>=1.2.3",
    "sounddevice>=0.5.6",
]

[project.scripts]
speech-to-text = "speech_to_text:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
