[project]
name = "image_create_edit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Diogo Passos Perdigão Britto", email = "diogopbritto@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
]

[project.scripts]
image-create-edit = "image_create_edit:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

